[package]
name = "api-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
axum = "0.6.1"
dotenv = "0.15.0"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "postgres", "offline"] }
tokio = { version = "1.23.0", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.3.5", features = ["cors"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
